<?xml version="1.0" encoding="UTF-8"?><testrun name="MemberServiceTest (5)" project="hello-spring" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.example.demo.service.MemberServiceTest" time="0.802" displayname="MemberServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.MemberServiceTest]">
    <testcase name="중복_회원_예외" classname="com.example.demo.service.MemberServiceTest" time="0.798" displayname="중복_회원_예외()" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.MemberServiceTest]/[method:중복_회원_예외()]">
      <failure>
        <expected>"이미 존재하는 회원입니다.ㅏㅏㅏㅏ"</expected>
        <actual>"이미 존재하는 회원입니다."</actual>
        org.opentest4j.AssertionFailedError: &#13;
expected: "이미 존재하는 회원입니다.ㅏㅏㅏㅏ"&#13;
 but was: "이미 존재하는 회원입니다."&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)&#13;
	at com.example.demo.service.MemberServiceTest.중복_회원_예외(MemberServiceTest.java:63)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
    <testcase name="회원가입" classname="com.example.demo.service.MemberServiceTest" time="0.004" displayname="회원가입()" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.MemberServiceTest]/[method:회원가입()]"/>
  </testsuite>
</testrun>
